services:
  catalogue:
    build: ./catalogue
    image: sreenivaschitti/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./user
    image: sreenivaschitti/user:1.0.0
    container_name: user
    depends_on:
    - redis 

  cart:
    build: ./cart
    image: sreenivaschitti/cart:1.0.0
    container_name: cart
    depends_on:
    - redis

  shipping:
    build: ./shipping
    image: sreenivaschitti/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql 
    - cart

  payment:
    build: ./payment
    image: sreenivaschitti/payment:1.0.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "rabbitmq"
      AMQP_PASS: "roboshop123"

    depends_on:
    - rabbitmq
    - cart
    - user

  frontend:
    build: ./frontend
    image: sreenivaschitti/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user 
    - cart
    - shipping
    - payment

  mongodb:
    build: ./mongodb
    image: sreenivaschitti/mongodb:1.0.0 
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis

  mysql:
    build: ./mysql
    image: sreenivaschitti/mysql:1.0.0
    container_name: mysql 


  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop 
      container_name: rabbitmq

networks:
  default:
    driver: bridge
    name: roboshop
    external: false    
